ChckLst/urls.py
from django.contrib import admin
from django.urls import include, path
from django_registration.backends.one_step.views import RegistrationView

urlpatterns = [
    path('accounts/register/',
        RegistrationView.as_view(success_url='/checklists'),
        name='django_registration_register'),
    path('accounts/', include('django_registration.backends.one_step.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('checklists/', include('checklist.urls')),
    path('admin/', admin.site.urls),
]

checklist/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

urlpatterns = [
    path('', views.checklists, name='checklists'),
    path('books/', login_required(views.BookListView.as_view()), name='books'),
    path('movies/', login_required(views.MovieListView.as_view()), name='movies'),
    path('food/', login_required(views.FoodListView.as_view()), name='food'),
    path('drinks/', login_required(views.DrinkListView.as_view()), name='drinks'),
    path('stats/', login_required(views.stats), name='stats'),
    path('random_book/', views.random_book, name='random_book'),
    path('book_checkbox/', views.book_checkbox, name='book_checkbox'),
    path('random_movie/', views.random_movie, name='random_movie'),
    path('movie_checkbox/', views.movie_checkbox, name='movie_checkbox'),
    path('random_dish/', views.random_dish, name='random_dish'),
    path('food_checkbox/', views.food_checkbox, name='food_checkbox'),
    path('random_drink/', views.random_drink, name='random_drink'),
    path('drink_checkbox/', views.drink_checkbox, name='drink_checkbox'),
]

checklist/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django_countries.fields import CountryField


# BOOKS Models --------------------------------------------------------------------------------

class Author(models.Model):
    name = models.CharField(max_length=100)

    class Meta(object):
        ordering = ['name']

    def __str__(self):
        return self.name


class B_Genre(models.Model):
    genre = models.CharField(max_length=100)

    def __str__(self):
        return self.genre

    class Meta(object):
        ordering = ['genre']


class Book(models.Model):

    order = models.PositiveIntegerField(default=0)
    title = models.CharField(max_length=200)
    author = models.ManyToManyField(Author)
    genre = models.ManyToManyField(B_Genre, blank=True)

    def __str__(self):
        return self.title

    class Meta(object):
        ordering = ['order']

    def display_author(self):
        return ', '.join(author.name for author in self.author.all())

    def display_genre(self):
        return ', '.join(genre.genre for genre in self.genre.all()[:3])

    display_author.short_description = 'Author'
    display_genre.short_description = 'Genre'


# MOVIES Models --------------------------------------------------------------------------------

class M_Genre(models.Model):
    genre = models.CharField(max_length=100)

    class Meta(object):
        ordering = ['genre']

    def __str__(self):
        return self.genre


class Movie(models.Model):

    order = models.PositiveIntegerField(default=0, blank=False, null=False)
    title = models.CharField(max_length=200)
    year = models.IntegerField()
    genre = models.ManyToManyField(M_Genre, blank=True)

    class Meta(object):
        ordering = ['order']

    def __str__(self):
        return self.title

    def display_genre(self):
        return ', '.join(genre.genre for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genre'


# FOOD Models ----------------------------------------------------------------------------------

class Ingredient(models.Model):
    ingredient = models.CharField(max_length=100)

    class Meta(object):
        ordering = ['ingredient']

    def __str__(self):
        return self.ingredient


class F_Kind(models.Model):
    food_kind = models.CharField(max_length=100)

    class Meta(object):
        ordering = ['food_kind']

    def __str__(self):
        return self.food_kind


class Food(models.Model):

    order = models.PositiveIntegerField(default=0, blank=False, null=False)
    name = models.CharField(max_length=200)
    country = CountryField(blank=True)
    food_kinds = models.ManyToManyField(F_Kind, blank=True)
    food_ingredients = models.ManyToManyField(Ingredient, blank=True)

    class Meta(object):
        ordering = ['order']
        verbose_name = 'Food'
        verbose_name_plural = 'Food'

    def __str__(self):
        return self.name

    def display_kind(self):
        return ', '.join(food_kinds.food_kind for food_kinds in self.food_kinds.all()[:3])

    display_kind.short_description = 'Kind'


# DRINKS Models --------------------------------------------------------------------------------

class D_kind(models.Model):
    drink_kind = models.CharField(max_length=100)

    class Meta(object):
        ordering = ['drink_kind']

    def __str__(self):
        return self.drink_kind


class Drink(models.Model):

    order = models.PositiveIntegerField(default=0, blank=False, null=False)
    name = models.CharField(max_length=200)
    alcohol = models.BooleanField(default=False)
    country = CountryField(blank=True)
    drink_kinds = models.ManyToManyField(D_kind, blank=True)
    drink_ingredients = models.ManyToManyField(Ingredient, blank=True)

    class Meta(object):
        ordering = ['order']

    def __str__(self):
        return self.name

    def display_kind(self):
        return ', '.join(drink_kinds.drink_kind for drink_kinds in self.drink_kinds.all()[:3])

    display_kind.short_description = 'Type'


# User Profile Models -------------------------------------------------------------------------

class Choice(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    books = models.ManyToManyField(Book, blank=True)
    movies = models.ManyToManyField(Movie, blank=True)
    food = models.ManyToManyField(Food, blank=True)
    drinks = models.ManyToManyField(Drink, blank=True)

    def __str__(self):
        return 'User_choice'


@receiver(post_save, sender=User)
def create_choice(sender, instance, created, **kwargs):
    if created:
        Choice.objects.create(user=instance)


# Stats Model ---------------------------------------------------------------------------------

class Statistic(models.Model):
    user_id = models.OneToOneField(User, on_delete=models.CASCADE)
    num_books = models.PositiveIntegerField(default=0, blank=False, null=False)
    num_movies = models.PositiveIntegerField(default=0, blank=False, null=False)
    num_food = models.PositiveIntegerField(default=0, blank=False, null=False)
    num_drinks = models.PositiveIntegerField(default=0, blank=False, null=False)

    def __str__(self):
        return str(self.user_id.username)

checklist/views.py
import random
from collections import Counter, OrderedDict

import country_converter
from django.contrib.auth.models import User
from django.http import Http404, JsonResponse
from django.shortcuts import render
from django.views import generic

from .models import (B_Genre, Book, D_kind, Drink, F_Kind, Food, Ingredient,
                     M_Genre, Movie, Statistic)


class BookListView(generic.ListView):
    model = Book
    template_name = 'Books_checklist.html'


class MovieListView(generic.ListView):
    model = Movie
    template_name = 'Movies_checklist.html'


class FoodListView(generic.ListView):
    model = Food
    template_name = 'Food_checklist.html'


class DrinkListView(generic.ListView):
    model = Drink
    template_name = 'Drinks_checklist.html'


# GENERAL -------------------------------------------------------------------------------------

def count_all_obj(model):
    '''
    The function counts all model objects.
    It is created to make the code more concise.
    '''
    return model.objects.all().count()


def century_from_year(year):
    '''
    The function converts a numeric year value to latin Century value.
    It is used for Books and Movies detail stats.
    '''

    roman = OrderedDict()

    roman[1000] = 'M'
    roman[900] = 'CM'
    roman[500] = 'D'
    roman[400] = 'CD'
    roman[100] = 'C'
    roman[90] = 'XC'
    roman[50] = 'L'
    roman[40] = 'XL'
    roman[10] = 'X'
    roman[9] = 'IX'
    roman[5] = 'V'
    roman[4] = 'IV'
    roman[1] = 'I'

    def year_to_roman(year):
        for r in roman.keys():
            x, y = divmod(year, r)
            yield roman[r] * x
            year -= (r * x)
            if year <= 0:
                break

    return "".join([a for a in year_to_roman((year + 99) // 100)])


def del_none(*args):
    '''
    The function removes none values from Counter dictionary.
    '''

    for arg in args:
        if None in arg:
            del arg[None]


def percentage(part, whole):
    '''
    The function returns a percentage value from 0 to 100.
    '''

    return round(100 * part / whole)


def update_statistic(user):
    '''
    The function updates the Statistic model with the latest
    checklists counts for each user.
    '''
    Statistic.objects.update_or_create(
        user_id=user,
        defaults={
            'num_books': user.choice.books.count(),
            'num_movies': user.choice.movies.count(),
            'num_food': user.choice.food.count(),
            'num_drinks': user.choice.drinks.count(),
        }
    )


# Checklists ----------------------------------------------------------------------------------

def checklists(request):
    return render(request, 'checklists.html')


# Statictic -----------------------------------------------------------------------------------

def favorite_items(user, model):
    '''
    The function returns a str/tuple with the most popular
    characteristics of the predefined Checklist.
    Book > Popular genres -> str
    Movie > Popular genres, century -> tuple
    Food > Popular kinds, ingredients, country -> tuple
    Drink > Popular kinds, ingredients, country -> tuple
    '''

    if model == Book:
        books_id = user.choice.books.values_list('id', flat=True).order_by('id')
        books = model.objects.filter(id__in=books_id)
        genres = books.values_list('genre', flat=True).order_by('genre')
        fav_genres = Counter(genres)
        del_none(fav_genres)
        if fav_genres:
            return ', '.join(B_Genre.objects.get(id=k).genre for k in list(fav_genres.keys())[:3])
        else:
            return 'mark read books to get stats'
    elif model == Movie:
        movies_id = user.choice.movies.values_list('id', flat=True).order_by('id')
        movies = model.objects.filter(id__in=movies_id)
        genres = movies.values_list('genre', flat=True).order_by('genre')
        years = movies.values_list('year', flat=True).order_by('year')
        fav_genres = Counter(genres)
        fav_years = Counter(years)
        del_none(fav_genres, fav_years)
        nothing_to_show = 'mark watched movies to get stats'
        if fav_genres:
            return (
                ', '.join(M_Genre.objects.get(id=k).genre for k in list(fav_genres.keys())[:3]),
                century_from_year(int(list(fav_years.keys())[0]))
                )
        else:
            return (nothing_to_show, nothing_to_show)
    elif model == Food:
        food_id = user.choice.food.values_list('id', flat=True).order_by('id')
        food = model.objects.filter(id__in=food_id)
        kinds = food.values_list('food_kinds', flat=True).order_by('food_kinds')
        ingredients = food.values_list('food_ingredients', flat=True).order_by('food_ingredients')
        countries = food.values_list('country', flat=True).order_by('country')
        fav_kinds = Counter(kinds)
        fav_ingredients = Counter(ingredients)
        fav_country = Counter(countries)
        del_none(fav_kinds, fav_country, fav_ingredients)
        nothing_to_show = 'mark eaten dishes to get stats'
        need_more_choices = 'mark more eaten dishes to get these stats'
        if fav_country:
            if len(fav_kinds) > 2 and len(fav_ingredients) > 2:
                return (
                    ', '.join(F_Kind.objects.get(id=k).food_kind for k in list(fav_kinds.keys())[:3]),
                    ', '.join(Ingredient.objects.get(id=k).ingredient for k in list(fav_ingredients.keys())[:3]),
                    country_converter.convert(list(fav_country.keys())[0], src='ISO2', to='name_short')
                    )
            else:
                return (
                    need_more_choices,
                    need_more_choices,
                    country_converter.convert(list(fav_country.keys())[0], src='ISO2', to='name_short')
                    )
        else:
            return (nothing_to_show, nothing_to_show, nothing_to_show)
    elif model == Drink:
        drink_id = user.choice.drinks.values_list('id', flat=True).order_by('id')
        drinks = Drink.objects.filter(id__in=drink_id)
        kinds = drinks.values_list('drink_kinds', flat=True).order_by('drink_kinds')
        ingredients = drinks.values_list('drink_ingredients', flat=True).order_by('drink_ingredients')
        countries = drinks.values_list('country', flat=True).order_by('country')
        fav_kinds = Counter(kinds)
        fav_ingredients = Counter(ingredients)
        fav_country = Counter(countries)
        del_none(fav_kinds, fav_country, fav_ingredients)
        nothing_to_show = 'mark drinks you have tried to get stats'
        need_more_choices = 'mark more tried drinks to get these stats'
        if fav_country:
            if len(fav_kinds) > 2 and len(fav_ingredients) > 2:
                return (
                    ', '.join(D_kind.objects.get(id=k).drink_kind for k in list(fav_kinds.keys())[:3]),
                    ', '.join(Ingredient.objects.get(id=k).ingredient for k in list(fav_ingredients.keys())[:3]),
                    country_converter.convert(list(fav_country.keys())[0], src='ISO2', to='name_short')
                    )
            else:
                return (
                    need_more_choices,
                    need_more_choices,
                    country_converter.convert(list(fav_country.keys())[0], src='ISO2', to='name_short')
                    )
        else:
            return (nothing_to_show, nothing_to_show, nothing_to_show)
    else:
        return 'the given category does not exist'


def stats(request):

    users = User.objects.all()

    for i in users:
        update_statistic(i)

    users_count = count_all_obj(User)

    user = request.user

    user_num_books = Statistic.objects.get(user_id=user.id).num_books
    user_num_movies = Statistic.objects.get(user_id=user.id).num_movies
    user_num_food = Statistic.objects.get(user_id=user.id).num_food
    user_num_drinks = Statistic.objects.get(user_id=user.id).num_drinks

    stats_count = (user_num_books, user_num_movies, user_num_food, user_num_drinks)
    stats_exist = True
    if not any(stats_count):
        stats_exist = False

    if stats_exist:

        all_books = count_all_obj(Book)
        all_movies = count_all_obj(Movie)
        all_food = count_all_obj(Food)
        all_drinks = count_all_obj(Drink)

        less_read = Statistic.objects.filter(num_books__lt=user_num_books).count()
        less_watched = Statistic.objects.filter(num_movies__lt=user_num_movies).count()
        less_ate = Statistic.objects.filter(num_food__lt=user_num_food).count()
        less_drank = Statistic.objects.filter(num_drinks__lt=user_num_drinks).count()

        books_percent = percentage(less_read, users_count-1)
        movies_percent = percentage(less_watched, users_count-1)
        food_percent = percentage(less_ate, users_count-1)
        drinks_percent = percentage(less_drank, users_count-1)

        user_books_percent = percentage(user_num_books, all_books)
        user_movies_percent = percentage(user_num_movies, all_movies)
        user_food_percent = percentage(user_num_food, all_food)
        user_drinks_percent = percentage(user_num_drinks, all_drinks)

        fav_book_genres = favorite_items(user, Book)
        fav_movie_items = favorite_items(user, Movie)
        fav_food_items = favorite_items(user, Food)
        fav_drink_items = favorite_items(user, Drink)

        context = {
            'user_num_books': user_num_books,
            'user_num_movies': user_num_movies,
            'user_num_food': user_num_food,
            'user_num_drinks': user_num_drinks,
            'all_books': all_books,
            'all_movies': all_movies,
            'all_food': all_food,
            'all_drinks': all_drinks,
            'books_percent': books_percent,
            'movies_percent': movies_percent,
            'food_percent': food_percent,
            'drinks_percent': drinks_percent,
            'user_books_percent': user_books_percent,

checklist/templates/Books_checklist.html
{% extends "base_generic.html" %}
{% load static %}
{% load tags %}

{% block details %}
    <link rel="stylesheet" href="{% static 'Books.css' %}" media="screen">
{% endblock %}

{% block content %}
  <section class="u-align-center u-clearfix u-grey-10 u-section-1" src="" id="sec-889b">
      <div class="u-clearfix u-sheet u-valign-middle u-sheet-1">
          <h1 class="u-text u-title u-text-1">Books</h1>
          <p class="u-large-text u-text u-text-variant u-text-2">
            If you don’t like to read, you<br>haven’t found the right book.
          </p>
          <a href="#checklist" class="u-black u-btn u-btn-round u-button-style u-radius-5 u-btn-1">START</a>
      </div>
  </section>
  <div id="checklist"></div>
  <section class="u-align-left u-clearfix u-section-2" id="carousel_4e2f">
      <div class="u-clearfix u-sheet u-valign-middle u-sheet-1">
      <h5 class="u-text u-text-1">mark WHAT YOU'VE already READ</h5>
      {% if book_list %}
          <div class="u-expanded-width u-list u-repeater u-list-1">
              {% for book in book_list %}
                  <div class="u-align-left u-container-style u-list-item u-repeater-item">
                      {% is_marked book user as is_book_read_by_user %}
                      <div class="u-container-layout u-similar-container u-container-layout-1 book-click chcklist-el" data-read={{ is_book_read_by_user }} data-book={{ book.id }} style="cursor:pointer;">
                          <span class="u-icon u-text-black u-icon-1 book-read" {% if not is_book_read_by_user %} style="display:none" {% endif %}>
                              <img src="{% static 'images/checkbox.svg' %}" class="u-svg-link" preserveAspectRatio="xMidYMin slice" viewBox="0 0 512.001 512.001" style="">
                          </span>
                          <span class="u-icon u-icon-1 book-unread" {% if is_book_read_by_user %} style="display:none" {% endif %}>
                              <img src="{% static 'images/empty-checkbox.svg' %}" class="u-svg-link" preserveAspectRatio="xMidYMin slice" viewBox="0 0 512.001 512.001" style="">
                          </span>
                          <h5 class="u-text u-text-4">{{ book.title }}<br><span style="color: #6b6b6b; font-weight: normal;">by {{book.author.all|join:", "}}</span></h5>
                      </div>
                  </div>

              {% endfor %}
          </div>
      {% else %}
          <p>There are no books in the list.</p>
      {% endif %}
  </section>
  {% is_all_read user as is_all_read_by_user %}
  <section class="u-align-center u-clearfix u-section-4 random-book-section" id="sec-5043" data-all-read={{ is_all_read_by_user }}>
    <div class="u-align-center u-clearfix u-sheet u-sheet-1 all-is-not-read" {% if is_all_read_by_user %} style="display: none;" {% endif %}>
      <h2 class="u-align-center u-text u-text-1 title-discover"><span class="random-title">Discover your next great read!</span></h2>
      <p class="u-large-text u-text u-text-variant u-text-2">
        <span class="random-book" style="font-size: 1.5rem;">The secret of getting ahead is getting started</span>
      </p>
      <div class="u-black u-border-0 u-btn u-btn-round u-button-style u-radius-5 u-btn-1 random-book-click" ><span class="random-button">Sure!</span></div>
    </div>
    <div class="u-align-center u-clearfix u-sheet u-sheet-1 all-is-read" {% if not is_all_read_by_user %} style="display: none;" {% endif %}>
      <h2 class="u-align-center u-text u-text-1 title-discover"><span class="random-title">Nice Done! You have marked everything!</span></h2>
    </div>
  </section>

  <script>
    $(".book-click").click(function(){
        let is_read = $(this).data("read") === "True";
        let is_read_marker = $(this).find(".book-read");
        let is_unread_marker = $(this).find(".book-unread");
        let book_id = $(this).data("book");
        $.ajax({
          type: 'POST',
          url: '../book_checkbox/',
          data: {
            'book_id': book_id,
            'is_read': !is_read,
            'csrfmiddlewaretoken': '{{ csrf_token }}',
          },
          dataType: 'json',
          success: function (response) {
            let is_all_read = response["is-all-read"];
            if (is_all_read) {
              $(".random-book-section").data("all-read", "True");
              $(".random-title").text("Nice Done! You have marked everything!");
              $(".all-is-read").show();
              $(".all-is-not-read").hide();
            }
            else {
              $(".random-book-section").data("all-read", "False");
              $(".random-title").text("Discover your next great read!");
              $(".all-is-read").hide();
              $(".all-is-not-read").show();
            };
          },
        });
        if (is_read) {
          $(this).data("read", "False");
          is_read_marker.hide();
          is_unread_marker.show();
        }
        else {
          $(this).data("read", "True");
          is_read_marker.show();
          is_unread_marker.hide();
        };
    });
    $(".random-book-click").click(function(){
      $(".random-title").text("Your next book recommendation is");
      $(this).find(".random-button").text("Next!");
      $.ajax({
        type: 'GET',
        async: true,
        url: '../random_book/',
        data: "book=book-info;",
        success: function(data) {
            $(".random-book").text(data['random-book-info']);
        },
        dataType: 'json',
      });
    });
  </script>
{% endblock %}

checklist/templates/Drinks_checklist.html
{% extends "base_generic.html" %}
{% load static %}
{% load tags %}

{% block details %}
    <link rel="stylesheet" href="{% static 'Books.css' %}" media="screen">
{% endblock %}

{% block content %}
  <section class="u-align-center u-clearfix u-grey-10 u-section-1" src="" id="sec-889b">
      <div class="u-clearfix u-sheet u-valign-middle u-sheet-1">
          <h1 class="u-text u-title u-text-1">Drinks</h1>
          <p class="u-large-text u-text u-text-variant u-text-2">
            People who wonder if the glass is half empty<br>or full miss the point. The glass is refillable.
          </p>
          <a href="#checklist" class="u-black u-btn u-btn-round u-button-style u-radius-5 u-btn-1">START</a>
      </div>
  </section>
  <div id="checklist"></div>

  <section class="u-align-left u-clearfix u-section-2" id="carousel_4e2f">
      <div class="u-clearfix u-sheet u-valign-middle u-sheet-1">
      <h5 class="u-text u-text-1">mark WHAT YOU'VE already TASTED</h5>
      {% if drink_list %}
          <div class="u-expanded-width u-list u-repeater u-list-1">
              {% for drink in drink_list %}
                  <div class="u-align-left u-container-style u-list-item u-repeater-item">
                      {% is_marked drink user as is_drink_drunk_by_user %}
                      <div class="u-container-layout u-similar-container u-container-layout-1 drink-click chcklist-el" data-drunk={{ is_drink_drunk_by_user }} data-drink={{ drink.id }} style="cursor:pointer;">
                          <span class="u-icon u-text-black u-icon-1 drink-drunk" {% if not is_drink_drunk_by_user %} style="display:none" {% endif %}>
                              <img src="{% static 'images/checkbox.svg' %}" class="u-svg-link" preserveAspectRatio="xMidYMin slice" viewBox="0 0 512.001 512.001" style="">
                          </span>
                          <span class="u-icon u-icon-1 drink-undrunk" {% if is_drink_drunk_by_user %} style="display:none" {% endif %}>
                              <img src="{% static 'images/empty-checkbox.svg' %}" class="u-svg-link" preserveAspectRatio="xMidYMin slice" viewBox="0 0 512.001 512.001" style="">
                          </span>
                          <h5 class="u-text u-text-4">{{ drink.name }} <img src="{% static 'images/oversized-wine-glass (2).svg' %}" {% if not drink.alcohol %} style="width: 15px; display:none;" {% else %} style="width: 15px;" {% endif %}><br><img src="{% static 'images/map-placeholder.svg' %}" style="width: 15px; opacity: 0.5;"> <span style="color: #6b6b6b; font-weight: normal;">{{ drink.country.name }}</span>
                      </div>
                  </div>

              {% endfor %}
          </div>
      {% else %}
          <p>There are no drinks in the list.</p>
      {% endif %}
  </section>

  {% is_all_drunk user as is_all_drunk_by_user %}
  <section class="u-align-center u-clearfix u-section-4 random-drink-section" id="sec-5043" data-all-drunk={{ is_all_drunk_by_user }}>
    <div class="u-align-center u-clearfix u-sheet u-sheet-1 all-is-not-drunk" {% if is_all_drunk_by_user %} style="display: none;" {% endif %}>
      <h2 class="u-align-center u-text u-text-1 title-discover"><span class="random-title">Discover your next great drink!</span></h2>
      <p class="u-large-text u-text u-text-variant u-text-2">
        <span class="random-drink" style="font-size: 1.5rem;">The secret of getting ahead is getting started</span>
      </p>
      <div class="u-black u-border-0 u-btn u-btn-round u-button-style u-radius-5 u-btn-1 random-drink-click" ><span class="random-button">Sure!</span></div>
    </div>
    <div class="u-align-center u-clearfix u-sheet u-sheet-1 all-is-drunk" {% if not is_all_drunk_by_user %} style="display: none;" {% endif %}>
      <h2 class="u-align-center u-text u-text-1 title-discover"><span class="random-title">Nice Done! You have marked everything!</span></h2>
    </div>
  </section>

  <script>
    $(".drink-click").click(function(){
        let is_drunk = $(this).data("drunk") === "True";
        let is_drunk_marker = $(this).find(".drink-drunk");
        let is_undrunk_marker = $(this).find(".drink-undrunk");
        let drink_id = $(this).data("drink");
        $.ajax({
          type: 'POST',
          url: '../drink_checkbox/',
          data: {
            'drink_id': drink_id,
            'is_drunk': !is_drunk,
            'csrfmiddlewaretoken': '{{ csrf_token }}',
          },
          dataType: 'json',
          success: function (response) {
            let is_all_drunk = response["is-all-drunk"];
            if (is_all_drunk) {
              $(".random-drink-section").data("all-drunk", "True");
              $(".random-title").text("Nice Done! You have marked everything!");
              $(".all-is-drunk").show();
              $(".all-is-not-drunk").hide();
            }
            else {
              $(".random-drink-section").data("all-drunk", "False");
              $(".random-title").text("Discover your next great drink!");
              $(".all-is-drunk").hide();
              $(".all-is-not-drunk").show();
            };
          },
        });
        if (is_drunk) {
          $(this).data("drunk", "False");
          is_drunk_marker.hide();
          is_undrunk_marker.show();
        }
        else {
          $(this).data("drunk", "True");
          is_drunk_marker.show();
          is_undrunk_marker.hide();
        };
    });

    $(".random-drink-click").click(function(){
      $(".random-title").text("Your next drink recommendation is");
      $(this).find(".random-button").text("Next!");
      $.ajax({
        type: 'GET',
        async: true,
        url: '../random_drink/',
        data: "drink=drink-info;",
        success: function(data) {
            $(".random-drink").text(data['random-drink-info']);
        },
        dataType: 'json',
      });
    });
  </script>
{% endblock %}